#%RAML 1.0
title: flightType
types:
  flight: !include entity/flightType.raml
  

/flights:
  get:
    responses:
      200:
        body:
          application/json:
            type: flight[]
  /{ID}:
      get:
        responses:
          200:
            body:
              application/json:
                type: flight
      delete:
        responses:
          200:
            body:
              application/json:
                type: string
                displayName: "result"
                example: "not true delete"
  /partFlights:
    post:
      body:
        application/json:
          type: object
          properties:
            planeNumbers:
              type: array
              items: string
              displayName: "number of plane"
              example: ["string1", "string2", "string3"]
      responses:
          200:
            body:
              application/json:
                type: flight[]        
                          

                             